### ISSUE TITLE
[koko]: package app

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.3#22]
ship in KCI or make package in blueshellnext

**Comment by star-buck** [comment]
koko never finishes initializing

**Comment by star-buck** [comment]
still not building: https://launchpad.net/~blue-shell-next/+archive/ubuntu/builds/+packages

**Comment by apachelogger** [comment]
can't build because it is downloading files from the internet which is disallowed and cannot be overridden.

so...
right now cmake checks in cmake_current_binary_dir if the files are there. this path is potentially different across different builds (it definitely is across different architectures). what we need is cmake to also check in $cmake_source_dir/data or some other source bound path where we can provide the data so that cmake doesn't need to download them.
this ultimately will then also be the path where the data would be put for a release tarball.

**Comment by star-buck** [comment]
@vishesh: can you fix this?

**Comment by vHanda** [comment]
On Thu, Feb 12, 2015 at 3:16 PM, apachelogger <notifications@github.com>
wrote:

> can't build because it is downloading files from the internet which is
> disallowed and cannot be overridden.
>

Are you sure it cannot be?

I understand the need for this for the final release, but for CI systems?

> so...
> right now cmake checks in cmake_current_binary_dir if the files are there.
> this path is potentially different across different builds (it definitely
> is across different architectures). what we need is cmake to also check in
> $cmake_source_dir/data or some other source bound path where we can provide
> the data so that cmake doesn't need to download them.
>

done

It checks in the source directory.

> this ultimately will then also be the path where the data would be put for
> a release tarball.
>
>
Yup. But we aren't creating release tarballs right now.


-- 
Vishesh Handa

**Comment by star-buck** [comment]
so can it be packaged correctly now?

**Comment by star-buck** [comment]
build seems still failing:
https://launchpad.net/~blue-shell-next/+archive/ubuntu/builds/+sourcepub/4775584/+listing-archive-extra

**Comment by apachelogger** [comment]
should be fixed now

**Comment by star-buck** [comment]
@apachelogger : please ship in next KCI (preferably vivid from now on).

**Comment by star-buck** [comment]
packaged and finally starts, but shows no files (will do a new ticket for that saga to continue...)
